
SELECT info_cliente_seq.NEXTVAL, cliente_seq.NEXTVAL FROM DUAL;
SELECT sku_seq.NEXTVAL, slug_seq.NEXTVAL, producto_seq.NEXTVAL FROM DUAL;
SELECT pago_seq.NEXTVAL FROM DUAL;
SELECT pago_ord.NEXTVAL FROM DUAL;
